### ISSUE TITLE
Little problem with instalation

### ISSUE THREAD

**Issue by przemekwa** [lowleveldesign/diagnostics-kit#1]
Hello, I want to test Your solusion I download diagcastle-elasticsearch_1.0.0.0.zip from github realese. and I install on IIS 8.5. 

I have following error. 

![image](https://cloud.githubusercontent.com/assets/5380497/16039287/2b9da512-3229-11e6-9647-bfcd6d4b6492.png)

I don't change web.config.

Do You have some idea what to do?

**Comment by lowleveldesign** [comment]
You will need to modify the connection in web.config, in the line 16 you have a connection to localhost:

`16:  <elasticLogStore elasticUrl="http://localhost:9200" />`

If your elastic search requires some authentication you would also need to set the username and passwd attributes. Please have a look at the help page: <https://github.com/lowleveldesign/diagnostics-kit/wiki/3.3.log-store-elastic-search>

**Comment by lowleveldesign** [comment]
@przemekwa did it start working?

**Comment by lowleveldesign** [comment]
I haven't received any info - I hope it's working for you now. Closing the ticket.
