### ISSUE TITLE
Musketeer serviece monitoring

### ISSUE THREAD

**Issue by opoani** [lowleveldesign/diagnostics-kit#3]
Hi Sebastian

First of all many thanks for the SQL server update it works like a charm 8-)

I have an additional question related to musketeer and logging of services. 

In the wiki there is a config option include-services and I have tried to configure that to monitor all services that contains "Time"  this is my config 

```xml
<add key="lowleveldesign.diagnostics.url" value="http://localhost:82/" />
    <add key="job:iis-config-refresh-cron" value="0 0/10 * * * ?" />
    <add key="job:perf-monitor-cron" value="0 * * * * ?" />
    <add key="job:iis-logs-read-cron" value="0/30 * * * * ?" />
    <add key="job:check-updates" value="0 /6 * * * ?" />
    <add key="include-http-success-logs" value="false" />
    <add key="include-services" value="\bTime\b;"/>
```
but no traces of any services can be found in the castle site. Logs from IIS and so on are being picked up but performance data (status such as sopped / running and so on) is not picked up. 

It could be that i have missed something here (most likely) or can this  type of monitoring not be applied?

The intended use case is to be able to collect some general status about some critical third-party services, hence its not possible to add a harvester like I can for services where i can control the code.      

Many thanks //Anders

**Comment by lowleveldesign** [comment]
Hi Anders,

I'm happy SQL Server log store worked for you. As far as Musketeer is concerned I'm not sure what might be the reason for the logs not showing up. I will check tomorrow whether there is no problem in the code checking regexes. In the meantime please check if there are any error messages from Musketeer in the Application Event Log. 

Also, from time to time the performance counters on Windows systems become corrupted. You may check if you see the counters in the perfmon.exe (Musketeer is using Process(*)\% Processor Time and Process (*)\Working Set).  If you don't find those counters try rebuilding them: https://blogs.msdn.microsoft.com/oanapl/2009/04/24/fix-corrupted-performance-counters/. You may also check the .NET counters as Musketeer will soon start using them: http://stackoverflow.com/questions/29074047/net-clr-performance-counters-missing.

**Comment by lowleveldesign** [comment]
@opoani I've checked the regex engine and it seems to be working correctly. Please check the Application eventlog for messages from the Musketeer service - there should be somewhere info that the service was skipped.

**Comment by opoani** [comment]
Yes , you are right for some reason it logs an unhandled exception for the job (Quartz) related to reading  the status of the service so I will investigate
Thanks  //Anders

Från: Sebastian Solnica [mailto:notifications@github.com]
Skickat: den 11 augusti 2016 14:42
Till: lowleveldesign/diagnostics-kit <diagnostics-kit@noreply.github.com>
Kopia: Anders Nilsson <Anders.Nilsson@soderbergpartners.se>; Mention <mention@noreply.github.com>
Ämne: Re: [lowleveldesign/diagnostics-kit] Musketeer serviece monitoring (#3)


@opoani<https://github.com/opoani> I've checked the regex engine and it seems to be working correctly. Please check the Application eventlog for messages from the Musketeer service - there should be somewhere info that the service was skipped.

**Comment by lowleveldesign** [comment]
Hi @opoani, any news about this one?

**Comment by opoani** [comment]
Sorry for missing to reply ... it works it was a issue not related to the Musketeer service that caused not all events picked up. You can close this and mark it as resolved . Many thanks Anders

**Comment by lowleveldesign** [comment]
I'm glad to hear that. Thanks
