### ISSUE TITLE
Elasticsearch 5.x support

### ISSUE THREAD

**Issue by beatcracker** [lowleveldesign/diagnostics-kit#4]
It looks like only Elasticsearch 2.x is supported. I've got this error with Elasticsearch 5.x:

```
[PipelineException: Failed sniffing cluster state.]
   Elasticsearch.Net.RequestPipeline.Sniff() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:340
   Elasticsearch.Net.RequestPipeline.FirstPoolUsage(SemaphoreSlim semaphore) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:134
   Elasticsearch.Net.Transport`1.Request(HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:53
   Elasticsearch.Net.ElasticLowLevelClient.IndicesExists(String index, Func`2 requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:2514
   Nest.LowLevelDispatch.IndicesExistsDispatch(IRequest`1 p) in C:\code\elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:1242
   Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch(TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\code\elasticsearch-net\src\Nest\ElasticClient.cs:56
   LowLevelDesign.Diagnostics.LogStore.ElasticSearch.ElasticSearchClientConfiguration..cctor() in C:\a\1\s\LogStores\LowLevelDesign.Diagnostics.LogStore.ElasticSearch\ElasticSearchClientConfiguration.cs:77
```

It's probably related to this issue (using NEST 2.x): https://github.com/elastic/elasticsearch-net/issues/2339

I think that [wiki](https://github.com/lowleveldesign/diagnostics-kit/wiki/3.3.log-store-elastic-search) should be updated to reflect this, because currently it states

Requirements|
------------|
Elastic Search &gt;= 1.7.1|

, which is confusing, since given ElasticSearch versioning scheme it's easy to assume that 5.x is OK.

**Comment by lowleveldesign** [comment]
Yes, you are right - I haven't worked on the project for a while and the docs become outdated. I will update NEST to a newer version and test it a bit. I will also have a look at the performance problem you reported in another ticket. Be back soon :)

**Comment by beatcracker** [comment]
Thanks!

I'm not sure that you need to update NEST, because it looks like a lot of software is stuck with Elastic 2.x (e.g.: [Graylog](https://github.com/Graylog2/graylog2-server/issues/2942)) and this means one can use single Elastic 2.x cluster as a backend in this case. Ideally it would be great to support both 2.x and 5.x, but it feels like asking too much. It's just docs and Elastic versioning that tripped me.

Regarding performance issue, I'll try to test on a another machine, maybe it has nothing to do with your code at all.

**Comment by lowleveldesign** [comment]
@beatcracker I added support for 5.x. Unfortunately, it would be quite hard to support ES 2.x and 5.x at the same time. Thus, the newest version will work on 5.x only - I updated the docs adequately. 

While testing I also noticed that the newest NEST has better performance than the 2.x version. I remember I experience some performance degradation after upgrade to 2.x, but didn't really have time to investigate it. Now, everything seems to be back on track. 

Please test and let me know if this new version works for you.

**Comment by lowleveldesign** [comment]
@beatcracker I'm closing the ticket - I hope the solution worked for you. Let me know if you run into any issues.
