### ISSUE TITLE
Diagnostics Castle: very slow response time

### ISSUE THREAD

**Issue by beatcracker** [lowleveldesign/diagnostics-kit#5]
I've trying to use Diagnostics Castle with ElasticSearch 2.x and having strange issues. Every HTTP request, that goes through ASP.NET takes 2-3 minutes to complete. 

I've been able to narrow it using IIS failed Request Tracing to this:

|No.|EventName|Details|Time|
|---|---------|-------|----|
|89.|AspNetPipelineEnter|Data1="Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage"|13:48:32.604|
|90.|GENERAL_SET_RESPONSE_HEADER|HeaderName="Vary", HeaderValue="Accept", Replace="true"|13:49:56.620|

As you can see, it's stuck for a minute and half in the `Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage`. 

Do you have any idea why this happens and what I can do to fix this?

**Comment by lowleveldesign** [comment]
Could you please record in Fiddler all the requests made to and by Diagnostics Castle? You will need to slightly modify the Diagnostics Castle web.config and add following lines into it:

```
  <system.net>
    <defaultProxy>
      <proxy autoDetect="False" proxyaddress="http://127.0.0.1:8888" bypassonlocal="False" usesystemdefault="False" />
    </defaultProxy>
  </system.net>
```

If ES is deployed on the same machine please change its address in web.config from localhost to localhost.fiddler. When you have the recording you may send them to me via email lowleveldesign at gmail. Also, if feasible, you may upgrade the ES and use the newest version of Diagnostics Kit - in my tests it seems that newest NEST has much better performance on ES 5.x.

**Comment by lowleveldesign** [comment]
I'm closing due to the lack of activity.
